name: ESLint

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: npm lint
      run: |
        npm install
        npm run lint:js
