name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
        npm install
        npm run build
    - name: WordPress Plugin Deploy
      uses: 10up/actions-wordpress/dotorg-plugin-deploy@develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
