name: SCANOSS CI Scan

on: push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Scan
      run: docker run -v "$(pwd)":"/scanoss"
ghcr.io/scanoss/scanoss-py scan --output output.json .

    - uses: actions/upload-artifact@v3
      with:
        name: output.json
        path: output.json
